# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration) 
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test "src/Tests/Tests.csproj" -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput="coverage/report" -l trx
  displayName: 'dotnet test with coverage'
- script: dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools --version=4.0.0-rc4
  displayName: 'dotnet install report generator tool'
- script: tools/reportgenerator "-reports:*/report.cobertura.xml" "-targetdir:report" "-verbosity:Verbose"
  displayName: 'generate coverage report'

- task: PublishTestResults@1
  inputs: 
    testRunner: VSTest
    testResultsFiles: 'src/Tests/TestResults/*.trx'

# Publish Code Coverage Results
# Publish Cobertura or JaCoCo code coverage results from a build
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura' # Options: cobertura, jaCoCo
    summaryFileLocation: '**/report.cobertura.xml'
    reportDirectory: 'report'
