using DwC_A.Meta;
using System.Collections.Generic;
using System.IO;

namespace DwC_A.Builders
{
    /// <summary>
    /// This class is generated by the FileBuilder class and passed into the BuildRows method.
    /// </summary>
    public class RowBuilder
    {
        private readonly IFileMetaData fileMetaData;
        private IList<string> fields = new List<string>();
        private readonly TextWriter writer;

        internal RowBuilder(IFileMetaData fileMetaData, TextWriter writer)
        {
            this.writer = writer;
            this.fileMetaData = fileMetaData;
        }

        /// <summary>
        /// Use this method to add a data field to a row in a file.
        /// </summary>
        /// <param name="field">Object containing the data to write to the field.  Uses the ToString() method of the object to write to the file.</param>
        /// <returns>this</returns>
        public RowBuilder AddField(object field)
        {
            fields.Add(fileMetaData.FieldsEnclosedBy + field.ToString() + fileMetaData.FieldsEnclosedBy);
            return this;
        }

        /// <summary>
        /// Call this method to write the row to the file.
        /// </summary>
        public void Build()
        {
            writer.WriteLine(string.Join(fileMetaData.FieldsTerminatedBy, fields));
        }
    }
}
